export const ActionTypes = {
    SET_TASKS_LOADING: "BOARD__SET_TASKS_LOADING",
    SET_TASKS: "BOARD__SET_TASKS",
    SET_TASK: "BOARD__SET_TASK",
    SET_TASKS_ERROR: "BOARD__TASKS_SET_ERROR",
    FETCH_TASKS: "BOARD__FETCH_TASKS",
    FETCH_TASK: "BOARD__FETCH_TASK",
    TASK_CREATE: "BOARD__TASK_CREATE",
    TASK_UPDATE: "BOARD__TASK_UPDATE",
    TASK_DELETE: "BOARD__TASK_DELETE"
};
