export const ActionTypes = {
    FETCH_TASKS: 'BOARD__FETCH_TASKS',
    FETCH_TASK: 'BOARD__FETCH_TASK',
    TASKS_LOADING: 'BOARD__TASKS_LOADING',
    SET_TASKS: 'BOARD__SET_TASKS',
    SET_TASK: 'BOARD__SET_TASK',
    TASKS_SET_ERROR: 'BOARD__TASKS_SET_ERROR',
    TASK_CREATE: 'BOARD__TASK_CREATE',
    TASK_UPDATE: 'BOARD__TASK_UPDATE',
    TASK_DELETE: 'BOARD__TASK_DELETE'
};