export const ActionTypes = {
    LOGIN: "AUTH__LOGIN",
    LOGOUT: "AUTH__LOGOUT",
    FORM_SET_LOADING: "AUTH__FORM_SET_LOADING",
    FORM_SET_ERROR: "AUTH__FORM_SET_ERROR",
    SET_AUTH_USER: "AUTH__SET_AUTH_USER",
};
